name: Main

on: [push]

jobs:
  cancel:
    runs-on: ubuntu-latest
    name: Cancel
    timeout-minutes: 3
    steps:
      # To use this repository's private action, you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test Step
        uses: ./ # Uses an action in the root directory
        with:
          accessToken: ${{ secrets.GITHUB_TOKEN }}
